apiVersion: v2
name: neuvector
description: A Helm chart for NeuVector deployment on k3s with Rancher Fleet integration
type: application
version: 0.1.0
appVersion: "2.8.3"
dependencies:
  - name: core
    version: 2.8.3
    repository: https://neuvector.github.io/neuvector-helm/
    alias: neuvector-core
    condition: neuvector.enabled

